### ISSUE TITLE
Check `fit_selection` and `center_selection` only when fitting and/or centering were requested.

### ISSUE THREAD

**Issue by pgbarletta** [bioexcel/biobb_analysis#11]
Hi!

This keeps biting me and I find it strange to specify `fit_selection` and `center_selection` when I'm not actually fitting or centering anything.

https://github.com/bioexcel/biobb_analysis/blob/aad7e19e63d4092f19aac8eb5d83b6c933d85b3e/biobb_analysis/gromacs/gmx_image.py#L107-L108

Thanks,

**Comment by gbayarri** [comment]
Hi @pgbarletta , can you please specify what you actually need? Do you have an example with this issue?

Thanks.

**Comment by pgbarletta** [comment]
Say:
```
make_whole = GMXImage(
    input_traj_path=xtc,
    input_index_path=ndx,
    input_top_path=tpr,
    output_traj_path=out_xtc,
    properties={
        "fit_selection": "complex",
        "center_selection": "complex",
        "output_selection": "complex",
        "ur": "compact",
        "pbc": "whole",
        "center": False,
    },
)
make_whole.launch()
```
I'm not centering, nor fitting (biobb will insert this into the cmd line to run: `-fit none -nocenter`), yet I have to include these properties:
```
        "fit_selection": "complex",
        "center_selection": "complex",
```
or else I get an exception thrown:
```
 GMXImage: Incorrect selection provided, exiting
```

or is there some other way of doing this that I'm missing?

Thanks.

**Comment by gbayarri** [comment]
Hi, we will add some conditionals to check if fit and center are provided:

[biobb_analysis/biobb_analysis/gromacs/gmx_image.py](https://github.com/bioexcel/biobb_analysis/blob/aad7e19e63d4092f19aac8eb5d83b6c933d85b3e/biobb_analysis/gromacs/gmx_image.py#L103-L104)

In case one or the two of them are not provided, they won't be mandatory anymore. We will do some modifications in the selections building as well:

[biobb_analysis/biobb_analysis/gromacs/gmx_image.py](https://github.com/bioexcel/biobb_analysis/blob/aad7e19e63d4092f19aac8eb5d83b6c933d85b3e/biobb_analysis/gromacs/gmx_image.py#L127-L130)

We will have it available for the next release.

Thanks!

**Comment by gbayarri** [comment]
Hi, we have modified the code and it will be integrated in the next release.

If you want to test it before the new release, you can do a git pull.

I close the issue, but don't hesitate to re-open it in case you find something more.
