### ISSUE TITLE
Selection not working on gmx_trjconv_trj if index file not given as input

### ISSUE THREAD

**Issue by adamhospital** [bioexcel/biobb_analysis#12]
If index file (input_index_path) not given (optional), the selection doesn't work. 

https://github.com/bioexcel/biobb_analysis/blob/ca820caf2afd9fdcea740051ec3150e86e70b3f7/biobb_analysis/gromacs/gmx_trjconv_trj.py#L22 

Two possible solutions:

1) Add a new input (optional?) input_top_path (same as gmx_trjconv_str)
2) Explicitly inform the user about the mandatory index file if a selection is needed

**Comment by gbayarri** [comment]
fixed, will be available in the next release
