### ISSUE TITLE
GMXImage: new handling of selections breaks -pbc cluster

### ISSUE THREAD

**Issue by pgbarletta** [bioexcel/biobb_analysis#13]
Hi,
this:
https://github.com/bioexcel/biobb_analysis/blob/844b8801c568b03985ff8b7d31e781f3477d336e/biobb_analysis/gromacs/gmx_image.py#L126-L136

breaks `-pbc cluster` since when using this option, both `center` and `fit` are disabled, but still 2 selections are needed (1 for clustering and another one for the output), and now only `self.output_selection` is used. This used to work fine if one set `center_selection`:
```
####### old version of `launch()` #######
        # If fitting provided, echo fit_selection
        if self.fit == 'none':
            selections = '\"' + self.center_selection + '\" \"' + self.output_selection + '\"'
        else:
            selections = '\"' + self.fit_selection + '\" \"' + self.center_selection + '\" \"' + self.output_selection + '\"'
```

Can we just perhaps get a new `cluster_selection`?
Thanks.

**Comment by gbayarri** [comment]
Hi,

We will take a look for the next release. 

But fell free to make your own pull request with all the options you need.

Best.

**Comment by pgbarletta** [comment]
Thanks!
