### ISSUE TITLE
Add Amber syntax atoms selection mask argument to the `cpptraj_*` functions.

### ISSUE THREAD

**Issue by ndonyapour** [bioexcel/biobb_analysis#16]
Hello,

I'm trying to use the `cpptraj_*` methods in our molecular modeling workflow and I need to use the Amber syntax masks for atoms selection, but the `mask` argument in `cpptraj_*` allows for a set of predefined constant options ([for example](https://biobb-analysis.readthedocs.io/en/latest/ambertools.html#module-ambertools.cpptraj_strip)). Is it possible to add another argument that would allow for the Amber format mask? 

Also, I'd like to use `cpptraj_rms` function with `nofit`, `norotate`, and `nomod` options. I have made changes to the `cpptraj_*` codes to have these functionalities and if you would like I can submit a PR.

Best,
Nazanin

**Comment by gbayarri** [comment]
Hi, @ndonyapour 

Can you please submit your PR?

Thanks!

**Comment by ndonyapour** [comment]
I submitted PR https://github.com/bioexcel/biobb_analysis/pull/17.

Thanks!
Nazanin

**Comment by gbayarri** [comment]
Merged into master.

Thanks!

PS - For future pull requests, there is no need to modify the json schemas, we generate them automatically from the python docstring for each tool.
