### ISSUE TITLE
Add Command line documentation.

### ISSUE THREAD

**Issue by PauAndrio** [bioexcel/biobb_analysis#2]
Check the biobb_io repository as an example for the Command line and readme.md documentation.
Also check the new changes in the command line interface:
- New group for arguments.
- Increased line lenght in help.

**Comment by gbayarri** [comment]
I did 3 blocks as an example:
https://biobb-analysis.readthedocs.io/en/latest/command_line.html

Should we add input/ouput documentation in this command line part? I think it should be a new section (named input/output?) with the description of the files and the accepted formats.

**Comment by gbayarri** [comment]
Added _I / O Arguments_ section in command line documentation:
https://biobb-analysis.readthedocs.io/en/latest/command_line.html
