### ISSUE TITLE
Make "input_top_path" optional in gmx_image

### ISSUE THREAD

**Issue by PabloNA97** [bioexcel/biobb_analysis#21]
"gmx trjconv" input structure file (-s) is Optional (see [manual](https://manual.gromacs.org/current/onlinehelp/gmx-trjconv.html)). However when using gmx trjconv through biobb this argument is compulsory ("input_top_path"). In general this is not an issue, but if one wants to use (-pbc nojump) and use the first frame as reference, the easiest thing is to provide no structure file (see [manual](https://manual.gromacs.org/current/onlinehelp/gmx-trjconv.html)). There might be other cases in which not providing an input topology file triggers a wanted behaviour like this. (For this example there is a workaround, but I thought that maybe making the parameter optional is easier)

**Comment by PauAndrio** [comment]
That's correct Pablo. I will announce this here when it is fixed.
